### ISSUE TITLE
FCM Integration

### ISSUE THREAD

**Issue by jimmyleonardo** [mixpanel/sample-android-mixpanel-integration#14]
Hi, I can't find integration FCM in your project. Because the docs using GCM.

Thanks

**Comment by patedit** [comment]
Hi @jimmyleonardo! Have you read the information posted here? https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0

I'll update the README file in this repository. Let me know if you have more questions

**Comment by jimmyleonardo** [comment]
Hi @patedit , Thanks for reply.
I already follow your instruction from https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0

But when we trying to send push notification from dashboard, we select the user has been intergrated with those code, Mixpanel still not set the user doesn't have device token and the user still not qualify.

Please advice!

**Comment by patedit** [comment]
Could you enable debugging on your app and check out your logcat session? Add the following tag to you `AndroidManifest.xml` file to make the SDK more verbose:

```
<meta-data android:name="com.mixpanel.android.MPConfig.EnableDebugLogging"
            android:value="true" />
```

Do you see the following line printed?
https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelFCMMessagingService.java#L136

In your logcat you should see a message from `FirebaseApp` printing whether it was initialized successfully or not. Let me know what you find!

**Comment by jimmyleonardo** [comment]
Hi @patedit . 
Here my log 
**2019-02-25 11:13:07.368 5190-5190/? I/FirebaseInitProvider: FirebaseApp initialization successful**

But there's no log about
**MPLog.d(LOGTAG, "MP FCM new push token: " + token);**

Thanks

**Comment by patedit** [comment]
Hi @jimmyleonardo ! Notice that that log will only be printed once per install. Seems that Google Play Services are properly installed and Firebase was initialized successfully. The only things that could be happening are:
a) Forgot to add `MixpanelFCMMessagingService` to your `AndroidManifest.xml`
b) Debugging is not enabled for the SDK. Thus, that log won't be shown on your logcat.
c) The user has a token already - could you double check your profile on mixpanel.com? As I said, that log will only be shown once per install.

Let me know what you find :) Thank you!

**Comment by jimmyleonardo** [comment]
Hi @patedit 
a. I already add service in my AndroidManifest.xml
`<service
            android:name="com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService"
            android:enabled="true"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>`
b. Already add
`<meta-data android:name="com.mixpanel.android.MPConfig.EnableDebugLogging"
            android:value="true" />`
c. We already check on dashboard, but the user still not qualify (not have token).

**Comment by patedit** [comment]
Can you shoot me an e-mail to sergio.alonso [at] mixpanel [dot] com ?

**Comment by hengkiardo** [comment]
Hi @patedit I'm colleague @jimmyleonardo 
please check your email ya, we have been send an email to you.

Thanks

**Comment by jimmyleonardo** [comment]
Hi @patedit , I want to ask this code below when migrate to FCM

`public void registerPush(GoogleCloudMessaging gcm){
    String registrationId = gcm.register("YOUR_SENDER_ID");
    MixpanelAPI.People people = mMixpanel.getPeople();
    people.identify("USER_DISTINCT_ID");
    people.setPushRegistrationId(registrationId);
}`

I think, We must put this code for setPushRegistrationId with FCM.
But the Docs still using GCM, can you help me how to get registrationId with FCM?

Thanks

**Comment by patedit** [comment]
Oh, that might be it. GCM can't co-exist with FCM. I'll reply to you on the e-mail.

**Comment by patedit** [comment]
Issue has been solved offline
