### ISSUE TITLE
session manager?

### ISSUE THREAD

**Issue by sirvon** [mixpanel/sample-android-mixpanel-integration#5]
Whats the big deal with session manager?

Whats the use case, why is it valuable?

Thanks

**Comment by joeatwork** [comment]
For some folks, an idea of how long a "user session" takes in one of their apps is a valuable metric for how their product is doing. While there is no idea of a session in Mixpanel (and user session doesn't really map all that naturally to how people use their Android phones) we put the SessionManager class in here to demonstrate how people might collect that sort of information.

We rarely advise customers to rely on the idea of session as success on any of our platforms (we usually recommend that folks focus on outcomes, things that are wins for their customers or their applications, and interventions that could lead to outcomes) but we also believe that folks should be able to use Mixpanel to answer any questions that they might have, and we wanted to show it was possible (and simple) to get that kind of metric.

Unless you're already interested in the idea of a session, or session length is an outcome you want to measure, you shouldn't have to worry about it.

Folks interested in timing, but less attached to the classic session metric, might want to use the built in `timeEvent` method in recent android releases, which is a more general mechanism that is easier to target on what you want for your users.
